### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by msandbothe** [fio4ri/FavoritePokemon#9]
Hey this is msandbot. I noticed that cmu finally deleted my contrib space. I was a bit sad that people wouldn't get to use this anymore. Seeing it duplicated here and with more work to improve it makes me happy. Thanks for continuing my work. I didn't think it would be as popular as it was when I quickly coded it up.

**Comment by fio4ri** [comment]
You are welcome! I just rewrote it again on my local copy in order to add a few more changes I really wanted to see. I will commit it to github soon.
